//! Auto-generated by factorio-rs. Do not edit by hand.
//!
//! Control-stage exports are at the crate root and lower to `remote.call`.
//! Shared exports mirror `__mod__/lua/...` require paths.
//! `pub mod remote` re-exports root remotes for compatibility.

#[allow(unused_variables)]
pub fn greet(name: &str) {}

pub mod remote {
    pub use super::greet;
}

pub mod shared {
    pub mod api {
        pub const VERSION: i32 = 0;
        #[allow(unused_variables)]
        pub fn greet(name: &str) {}
    }
}
