use factorio_ir::{
    block::Block, expression::Expression, function::Function, literal::Literal, module::Module,
    operator::Operator, scope::Scope, statement::Statement, structure::Struct,
};

use crate::generator::error::{LuaGeneratorError, LuaGeneratorResult};

pub mod error;

pub struct LuaGenerator {
    output: String,
    indent_level: usize,
    /// Rewrites `StructName.associated` paths while generating struct methods.
    struct_table_context: Option<(String, String)>,
}

impl Default for LuaGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl LuaGenerator {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
            struct_table_context: None,
        }
    }

    pub const INDENT: &'static str = "\t";

    /// Returns a string indented to [LuaGenerator::indent_level].
    fn indent(&self) -> String {
        Self::INDENT.repeat(self.indent_level)
    }

    /// Writes a line of text to [LuaGenerator::output] terminated by a newline `\n`.
    fn write_line(&mut self, line: &str) {
        if !line.is_empty() {
            self.output.push_str(&self.indent());
            self.output.push_str(line);
        }
        self.output.push('\n');
    }

    pub const MODULE_META_START: &'static str =
        concat!("-- Generated by cargo-factorio@", env!("CARGO_PKG_VERSION"));

    fn generate_module_meta(module: &Module) -> String {
        let module_line = format!("-- Module: `{}`", module.name);
        format!("{}\n{}", Self::MODULE_META_START, module_line)
    }

    /// Returns the module identifier that exported symbols will be attached to, e.g
    /// `bound_detector` -> `boundDetector`, `player.extra_info` -> `playerExtraInfo`.
    fn module_identifier(module_name: &str) -> String {
        heck::AsLowerCamelCase(module_name.replace('.', "_")).to_string()
    }

    pub fn generate_module(&mut self, module: &Module) -> LuaGeneratorResult<String> {
        self.output.clear();
        self.indent_level = 0;

        let module_header = Self::generate_module_meta(module);
        self.output.push_str(&module_header);
        self.output.push('\n');

        self.generate_imports(&module.imports);
        self.generate_submodules(&module.submodules);

        for statement in &module.body.statements {
            self.generate_statement(statement, Some(module), None, Scope::Private)?;
        }

        let module_name = Self::module_identifier(&module.name);
        let (exporter_start, exporter_end) = Self::generate_symbol_exporter(&module_name);
        self.write_line(&exporter_start);

        for symbol in &module.symbols {
            self.generate_statement(
                &symbol.statement,
                Some(module),
                Some(&module_name),
                symbol.scope,
            )?;
        }

        self.write_line(&exporter_end);

        Ok(self.output.clone())
    }

    fn generate_imports(&mut self, imports: &[factorio_ir::module::ModuleImport]) {
        for import in imports {
            self.write_line(&format!(
                "local {} = require(\"{}\")",
                import.local, import.module
            ));

            for item in &import.items {
                self.write_line(&format!(
                    "local {} = {}.{}",
                    item.local, import.local, item.name
                ));
            }
        }

        if !imports.is_empty() {
            self.output.push('\n');
        }
    }

    fn generate_submodules(&mut self, submodules: &[String]) {
        for submodule in submodules {
            self.write_line(&format!("require(\"{submodule}\")"));
        }

        if !submodules.is_empty() {
            self.output.push('\n');
        }
    }

    /// Return the starting and ending lines for exporting symbols.
    fn generate_symbol_exporter(module_name: &str) -> (String, String) {
        (
            format!("local {module_name} = {{}}"),
            format!("return {module_name}"),
        )
    }

    fn generate_block(&mut self, block: &Block, module: Option<&Module>) -> LuaGeneratorResult<()> {
        for statement in &block.statements {
            self.generate_statement(statement, module, None, Scope::Private)?;
        }
        Ok(())
    }

    fn generate_statement(
        &mut self,
        statement: &Statement,
        module: Option<&Module>,
        module_name: Option<&str>,
        scope: Scope,
    ) -> LuaGeneratorResult<()> {
        match statement {
            Statement::FunctionDecl(function) => {
                self.generate_function(function, module, scope, module_name)?;
            }
            Statement::StructDecl(struct_decl) => {
                self.generate_struct(struct_decl, module, scope, module_name)?;
            }
            Statement::VariableDecl { name, value, .. } => {
                let value = self.generate_expression(value);
                let line = match (scope, module_name) {
                    (Scope::Public, Some(module_name)) => {
                        format!("{module_name}.{name} = {value}")
                    }
                    _ => format!("local {name} = {value}"),
                };
                self.write_line(&line);
            }
            Statement::Assignment { target, value } => {
                let target = self.generate_expression(target);
                let value = self.generate_expression(value);
                self.write_line(&format!("{target} = {value}"));
            }
            Statement::Conditional {
                condition,
                then_block,
                else_block,
            } => {
                let condition = self.generate_expression(condition);
                self.write_line(&format!("if {condition} then"));

                self.indent_level += 1;
                for statement in then_block {
                    self.generate_statement(statement, module, module_name, Scope::Private)?;
                }
                self.indent_level -= 1;

                if else_block.is_empty() {
                    self.write_line("end");
                } else {
                    self.write_line("else");
                    self.indent_level += 1;
                    for statement in else_block {
                        self.generate_statement(statement, module, module_name, Scope::Private)?;
                    }
                    self.indent_level -= 1;
                    self.write_line("end");
                }
            }
            Statement::Return(value) => {
                let line = match value {
                    Some(value) => format!("return {}", self.generate_expression(value)),
                    None => "return".to_string(),
                };
                self.write_line(&line);
            }
            Statement::Expr(expression) => {
                self.write_line(&self.generate_expression(expression));
            }
        }

        Ok(())
    }

    fn generate_struct(
        &mut self,
        struct_decl: &Struct,
        module: Option<&Module>,
        scope: Scope,
        module_name: Option<&str>,
    ) -> LuaGeneratorResult<()> {
        if scope == Scope::Private && module_name.is_some() {
            return Err(LuaGeneratorError::StructLocalAndExported(
                struct_decl.name.clone(),
            ));
        }

        if let Some(module) = module {
            if module.is_imported_type_extension(struct_decl) {
                let table_path = module
                    .imported_item_local(&struct_decl.name)
                    .expect("imported type extension must resolve to a local binding")
                    .to_string();

                for method in &struct_decl.methods {
                    self.generate_table_method(method, &struct_decl.name, &table_path)?;
                }

                return Ok(());
            }
        }

        let table_path = match (scope, module_name) {
            (Scope::Public, Some(module_name)) => {
                format!("{module_name}.{}", struct_decl.name)
            }
            (Scope::Private, None) => struct_decl.name.clone(),
            (Scope::Public, None) => struct_decl.name.clone(),
            (Scope::Private, Some(_)) => unreachable!("handled above"),
        };

        let prefix = if scope == Scope::Private && module_name.is_none() {
            "local "
        } else {
            ""
        };

        self.write_line(&format!("{prefix}{table_path} = {{}}"));

        for (name, value) in &struct_decl.constants {
            let value = self.generate_expression(value);
            self.write_line(&format!("{table_path}.{name} = {value}"));
        }

        for method in &struct_decl.methods {
            self.generate_table_method(method, &struct_decl.name, &table_path)?;
        }

        Ok(())
    }

    fn generate_table_method(
        &mut self,
        func: &Function,
        struct_name: &str,
        table_path: &str,
    ) -> LuaGeneratorResult<()> {
        let function_uses_self = func
            .params
            .first()
            .is_some_and(|parameter| parameter.name == "self");

        let params = if function_uses_self {
            func.params
                .iter()
                .skip(1)
                .map(|parameter| parameter.name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        } else {
            func.params
                .iter()
                .map(|parameter| parameter.name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        };

        let separator = if function_uses_self { ":" } else { "." };
        self.write_line(&format!(
            "function {table_path}{separator}{}({params})",
            func.name
        ));

        self.struct_table_context = Some((struct_name.to_string(), table_path.to_string()));
        self.indent_level += 1;
        self.generate_block(&func.body, None)?;
        self.indent_level -= 1;
        self.struct_table_context = None;

        self.write_line("end");

        Ok(())
    }

    fn generate_function(
        &mut self,
        func: &Function,
        module: Option<&Module>,
        scope: Scope,
        module_name: Option<&str>,
    ) -> LuaGeneratorResult<()> {
        // We cannot have a private function and export it.
        if scope == Scope::Private && module_name.is_some() {
            return Err(LuaGeneratorError::FunctionLocalAndExported(
                func.name.clone(),
            ));
        }

        let prefix = match scope {
            Scope::Private => "local ",
            Scope::Public => "",
        };

        let function_uses_self = func
            .params
            .first()
            .is_some_and(|parameter| parameter.name == "self");

        let params = if function_uses_self && module_name.is_some() {
            func.params
                .iter()
                .skip(1)
                .map(|parameter| parameter.name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        } else {
            func.params
                .iter()
                .map(|parameter| parameter.name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        };

        let function_name = match module_name {
            Some(module_name) if function_uses_self => {
                format!("{module_name}:{}", func.name)
            }
            Some(module_name) => format!("{module_name}.{}", func.name),
            None => func.name.clone(),
        };

        self.write_line(&format!("{prefix}function {function_name}({params})"));

        self.indent_level += 1;
        self.generate_block(&func.body, module)?;
        self.indent_level -= 1;

        self.write_line("end");

        Ok(())
    }

    fn generate_expression(&self, expression: &Expression) -> String {
        match expression {
            Expression::Literal(literal) => self.generate_literal(literal),
            Expression::Identifier(name) => name.clone(),
            Expression::FieldAccess { base, field } => {
                let base = self.generate_expression(base);
                format!("{base}.{field}")
            }
            Expression::QualifiedPath { segments } => {
                if let Some((struct_name, table_path)) = &self.struct_table_context {
                    if segments
                        .first()
                        .is_some_and(|segment| segment == struct_name)
                    {
                        let suffix = segments
                            .get(1..)
                            .map_or_else(String::new, |rest| rest.join("."));
                        if suffix.is_empty() {
                            return table_path.clone();
                        }
                        return format!("{table_path}.{suffix}");
                    }
                }

                segments.join(".")
            }
            Expression::Call { func, args } => {
                let func = self.generate_expression(func);
                let args = args
                    .iter()
                    .map(|arg| self.generate_expression(arg))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{func}({args})")
            }
            Expression::MethodCall {
                receiver,
                method,
                args,
            } => {
                let receiver = self.generate_expression(receiver);
                let args = args
                    .iter()
                    .map(|arg| self.generate_expression(arg))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{receiver}:{method}({args})")
            }
            Expression::StructLiteral { fields } => {
                let fields = fields
                    .iter()
                    .map(|(name, value)| format!("{name} = {}", self.generate_expression(value)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{{ {fields} }}")
            }
            Expression::BinaryOp { lhs, op, rhs } => {
                let lhs = self.generate_expression(lhs);
                let rhs = self.generate_expression(rhs);
                let op = self.generate_operator(*op);
                format!("({lhs} {op} {rhs})")
            }
        }
    }

    fn generate_literal(&self, literal: &Literal) -> String {
        match literal {
            Literal::Int(value) => value.to_string(),
            Literal::Float(value) => value.to_string(),
            Literal::String(value) => format!("\"{}\"", escape_lua_string(value)),
        }
    }

    fn generate_operator(&self, operator: Operator) -> &'static str {
        match operator {
            Operator::Add => "+",
            Operator::Sub => "-",
            Operator::Mul => "*",
            Operator::Div => "/",
            Operator::Eq => "==",
        }
    }
}

fn escape_lua_string(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}
