use std::collections::BTreeMap;
use std::fmt::Write as _;

use factorio_ir::{locale::LocaleFile, module::Module, stage::Stage, statement::Statement};
use heck::AsLowerCamelCase;

use crate::{
    generator::LuaGenerator,
    pack::events::{EventRegistration, collect_event_registrations},
};

pub mod events;
pub mod exports;

/// A stage module and the public functions that should run when it is loaded.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StageModule {
    pub name: String,
    pub entry_functions: Vec<String>,
}

/// Options for [`emit_mod_tree`].
#[derive(Debug, Clone)]
pub struct EmitModOptions<'a> {
    pub mod_name: &'a str,
    pub module_prefix: &'a str,
    pub profile: &'a str,
    pub version: &'a str,
    pub title: &'a str,
    pub author: &'a str,
    pub factorio_version: &'a str,
    pub description: Option<&'a str>,
    /// When set, emit Rust-oriented comments in generated Lua (see CLI profiles).
    pub debug_level: Option<u8>,
}

impl<'a> EmitModOptions<'a> {
    #[must_use]
    pub const fn playground(mod_name: &'a str) -> Self {
        Self {
            mod_name,
            module_prefix: "",
            profile: "playground",
            version: "0.1.0",
            title: mod_name,
            author: "playground",
            factorio_version: "2.0",
            description: Some("Generated by the factorio-rs docs playground"),
            debug_level: None,
        }
    }
}

/// Returns module metadata if this module belongs to the given stage.
#[must_use]
pub fn collect_stage_module(module: &Module, stage: Stage) -> Option<StageModule> {
    if module.stage != stage {
        return None;
    }

    let entry_functions = module
        .symbols
        .iter()
        .filter_map(|symbol| {
            let Statement::FunctionDecl(function) = &symbol.statement else {
                return None;
            };
            Some(function.name.clone())
        })
        .collect();

    Some(StageModule {
        name: module.name.clone(),
        entry_functions,
    })
}

fn generated_header(profile: &str) -> String {
    format!(
        "-- Generated by factorio-rs@{}\n-- Profile: {profile}\n",
        env!("CARGO_PKG_VERSION"),
    )
}

/// Generate a stage entry file (`data.lua`, `settings.lua`, ...).
#[must_use]
pub fn generate_stage_entry_lua(
    mod_name: &str,
    stage_modules: &[StageModule],
    stage: Stage,
    module_prefix: &str,
    profile: &str,
) -> String {
    let mut output = generated_header(profile);

    let roots: Vec<&StageModule> = stage_modules
        .iter()
        .filter(|module| {
            !stage_modules.iter().any(|other| {
                other.name != module.name && module.name.starts_with(&format!("{}.", other.name))
            })
        })
        .collect();

    if roots.is_empty() {
        output.push_str("-- No modules registered for this stage.\n");
        return output;
    }

    for module in roots {
        let lua_path = prefixed_lua_path(&module.name, module_prefix);
        let raw_table_name = module_lua_identifier(&module.name);
        let table_name = if module_prefix.is_empty() {
            raw_table_name
        } else {
            format!("{module_prefix}_{raw_table_name}")
        };
        let _ = writeln!(
            output,
            "local {table_name} = require(\"__{mod_name}__/lua/{lua_path}\")"
        );
        for function in &module.entry_functions {
            let _ = writeln!(output, "{table_name}.{function}()");
        }
        output.push('\n');
    }

    let _ = stage;
    output
}

/// Generate root `control.lua` with event registration and remote interfaces.
#[must_use]
pub fn generate_control_lua(
    mod_name: &str,
    events: &[EventRegistration],
    remote_exports: &[exports::RemoteExport],
    module_prefix: &str,
    profile: &str,
) -> String {
    let mut output = generated_header(profile);
    if events.is_empty() && remote_exports.is_empty() {
        output.push_str("-- No event handlers or remote exports registered.\n");
        return output;
    }

    let generator = LuaGenerator::new();
    let mut emitted_requires: Vec<String> = Vec::new();

    for event in events {
        emit_module_require(
            &mut output,
            &mut emitted_requires,
            mod_name,
            &event.module,
            module_prefix,
        );
        let table_name = module_lua_identifier(&event.module);

        let _ = writeln!(
            output,
            "script.on_event(defines.events.{}, function(event)",
            event.event
        );
        let _ = writeln!(output, "\t{table_name}.{}(event)", event.handler);
        if let Some(filter) = &event.filter {
            let filter_lua = generator.generate_expression(filter);
            let _ = writeln!(output, "end, {filter_lua})");
        } else {
            let _ = writeln!(output, "end)");
        }
        output.push('\n');
    }

    let mut by_interface: BTreeMap<String, Vec<&exports::RemoteExport>> = BTreeMap::new();
    for export in remote_exports {
        emit_module_require(
            &mut output,
            &mut emitted_requires,
            mod_name,
            &export.module,
            module_prefix,
        );
        by_interface
            .entry(export.interface.clone())
            .or_default()
            .push(export);
    }

    for (interface, exports) in by_interface {
        let _ = writeln!(output, "remote.add_interface(\"{interface}\", {{");
        for export in exports {
            let table_name = module_lua_identifier(&export.module);
            let _ = writeln!(
                output,
                "\t{} = function(...)\n\t\treturn {table_name}.{}(...)\n\tend,",
                export.function, export.function
            );
        }
        let _ = writeln!(output, "}})\n");
    }

    output
}

fn emit_module_require(
    output: &mut String,
    emitted: &mut Vec<String>,
    mod_name: &str,
    module: &str,
    module_prefix: &str,
) {
    if emitted.contains(&module.to_string()) {
        return;
    }
    let lua_module_path = prefixed_lua_path(module, module_prefix);
    let require_path = format!("__{mod_name}__/lua/{lua_module_path}");
    let table_name = module_lua_identifier(module);
    let _ = writeln!(output, "local {table_name} = require(\"{require_path}\")");
    emitted.push(module.to_string());
}

/// Convert a dotted module name to a `/`-separated Lua path with optional prefix.
#[must_use]
pub fn prefixed_lua_path(module_name: &str, prefix: &str) -> String {
    if prefix.is_empty() {
        return module_name.replace('.', "/");
    }
    module_name.rfind('.').map_or_else(
        || format!("{prefix}_{module_name}"),
        |dot| {
            let dir = module_name[..dot].replace('.', "/");
            format!("{dir}/{prefix}_{}", &module_name[dot + 1..])
        },
    )
}

#[must_use]
pub fn module_lua_identifier(module_name: &str) -> String {
    AsLowerCamelCase(module_name.replace('.', "_")).to_string()
}

/// Merge locale files by `(lang, file)`.
#[must_use]
pub fn merge_locale_files(locales: &[LocaleFile]) -> Vec<LocaleFile> {
    let mut merged: BTreeMap<(String, String), LocaleFile> = BTreeMap::new();
    for locale in locales {
        let key = (locale.lang.clone(), locale.file.clone());
        merged
            .entry(key)
            .and_modify(|existing| existing.entries.extend(locale.entries.iter().cloned()))
            .or_insert_with(|| locale.clone());
    }
    merged.into_values().collect()
}

/// Build Factorio `info.json` contents.
#[must_use]
pub fn generate_info_json(
    name: &str,
    version: &str,
    title: &str,
    author: &str,
    factorio_version: &str,
    description: Option<&str>,
) -> String {
    let mut map = serde_json::Map::new();
    map.insert(
        "name".to_string(),
        serde_json::Value::String(name.to_string()),
    );
    map.insert(
        "version".to_string(),
        serde_json::Value::String(version.to_string()),
    );
    map.insert(
        "title".to_string(),
        serde_json::Value::String(title.to_string()),
    );
    map.insert(
        "author".to_string(),
        serde_json::Value::String(author.to_string()),
    );
    map.insert(
        "factorio_version".to_string(),
        serde_json::Value::String(factorio_version.to_string()),
    );
    map.insert(
        "dependencies".to_string(),
        serde_json::Value::Array(vec![serde_json::Value::String(format!(
            "base >= {factorio_version}"
        ))]),
    );
    if let Some(description) = description {
        map.insert(
            "description".to_string(),
            serde_json::Value::String(description.to_string()),
        );
    }
    let mut json = serde_json::to_string_pretty(&serde_json::Value::Object(map))
        .unwrap_or_else(|_| "{}".to_string());
    json.push('\n');
    json
}

/// Emit a full Factorio mod file tree from lowered IR modules.
///
/// Includes module Lua under `lua/`, root entry scripts, locale `.cfg`, and `info.json`.
///
/// # Errors
/// Returns `Err` if the module could not be generated.
pub fn emit_mod_tree(
    modules: &[Module],
    options: &EmitModOptions<'_>,
) -> Result<BTreeMap<String, String>, crate::LuaGeneratorError> {
    let mut out = BTreeMap::new();

    for module in modules {
        let mut generator = options.debug_level.map_or_else(
            || LuaGenerator::with_mod_name(options.mod_name),
            |level| LuaGenerator::with_mod_name_and_debug(options.mod_name, level),
        );
        generator = generator.with_profile(options.profile);
        let lua = generator.generate_module(module)?;
        let relative = format!("lua/{}.lua", module.name.replace('.', "/"));
        out.insert(relative, lua);
    }

    let events: Vec<EventRegistration> = modules
        .iter()
        .flat_map(collect_event_registrations)
        .collect();
    let remotes: Vec<exports::RemoteExport> = modules
        .iter()
        .flat_map(|module| exports::collect_remote_exports(module, options.mod_name))
        .collect();
    out.insert(
        "control.lua".to_string(),
        generate_control_lua(
            options.mod_name,
            &events,
            &remotes,
            options.module_prefix,
            options.profile,
        ),
    );

    for stage in Stage::SIDE_EFFECT_STAGES {
        let stage_modules: Vec<StageModule> = modules
            .iter()
            .filter_map(|module| collect_stage_module(module, stage))
            .collect();
        if stage_modules.is_empty() {
            continue;
        }
        let Some(file_name) = stage.entry_file_name() else {
            continue;
        };
        out.insert(
            file_name.to_string(),
            generate_stage_entry_lua(
                options.mod_name,
                &stage_modules,
                stage,
                options.module_prefix,
                options.profile,
            ),
        );
    }

    let locales: Vec<LocaleFile> = modules
        .iter()
        .flat_map(|module| module.locales.iter().cloned())
        .collect();
    for locale in merge_locale_files(&locales) {
        let path = format!("locale/{}/{}.cfg", locale.lang, locale.file);
        out.insert(path, locale.to_cfg());
    }

    out.insert(
        "info.json".to_string(),
        generate_info_json(
            options.mod_name,
            options.version,
            options.title,
            options.author,
            options.factorio_version,
            options.description,
        ),
    );

    Ok(out)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used, clippy::unwrap_used)]

    use factorio_ir::{
        block::Block,
        function::Function,
        module::{Module, Symbol},
        scope::Scope,
        stage::Stage,
        statement::Statement,
    };

    use super::{EmitModOptions, collect_event_registrations, emit_mod_tree, generate_control_lua};

    fn control_handler(module_name: &str, handler: &str, event: &str) -> Module {
        Module {
            name: module_name.to_string(),
            stage: Stage::Control,
            body: Block { statements: vec![] },
            symbols: vec![Symbol {
                scope: Scope::Public,
                statement: Statement::FunctionDecl(Function {
                    name: handler.to_string(),
                    params: vec![],
                    body: Block { statements: vec![] },
                    doc: None,
                    debug: None,
                    event: Some(event.to_string()),
                    event_filter: None,
                    export: None,
                    inline: false,
                }),
            }],
            imports: vec![],
            submodules: vec![],
            locales: vec![],
            pending_locales: vec![],
            vtables: vec![],
        }
    }

    #[test]
    fn control_lua_registers_events() {
        let module = control_handler(
            "control.on_init",
            "on_singleplayer_init",
            "on_singleplayer_init",
        );
        let events = collect_event_registrations(&module);
        let lua = generate_control_lua("playground", &events, &[], "", "debug");
        assert!(lua.contains("script.on_event(defines.events.on_singleplayer_init"));
        assert!(lua.contains("require(\"__playground__/lua/control/on_init\")"));
    }

    #[test]
    fn emit_mod_tree_includes_packaging_files() {
        let module = control_handler(
            "control.on_init",
            "on_singleplayer_init",
            "on_singleplayer_init",
        );
        let tree = emit_mod_tree(&[module], &EmitModOptions::playground("playground")).unwrap();
        assert!(tree.contains_key("control.lua"));
        assert!(tree.contains_key("info.json"));
        assert!(tree.contains_key("lua/control/on_init.lua"));
        assert!(tree["control.lua"].contains("script.on_event"));
        assert!(tree["info.json"].contains("\"name\": \"playground\""));
    }
}
