#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::panic_in_result_fn,
    dead_code
)]

use factorio_codegen::LuaGeneratorError;
use full_moon::{LuaVersion, parse_fallible};

/// Replace the crate-version header so snapshots do not churn on releases.
#[must_use]
pub fn normalize_generated_header(lua: &str) -> String {
    let mut out = String::with_capacity(lua.len());
    let mut lines = lua.split_inclusive('\n');
    if let Some(first) = lines.next() {
        if first.starts_with("-- Generated by factorio-rs@") {
            out.push_str("-- Generated by factorio-rs@VERSION");
            if first.ends_with('\n') {
                out.push('\n');
            }
        } else {
            out.push_str(first);
        }
    }
    for line in lines {
        out.push_str(line);
    }
    out
}

fn parse_errors(lua: &str) -> Option<String> {
    let result = parse_fallible(lua, LuaVersion::lua52());
    let errors = result.errors();
    if errors.is_empty() {
        None
    } else {
        Some(
            errors
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join("\n"),
        )
    }
}

/// Assert `lua` is a valid Lua 5.2 chunk (Factorio's baseline).
#[track_caller]
pub fn assert_lua_parses(lua: &str) {
    if let Some(errors) = parse_errors(lua) {
        panic!("emitted Lua failed to parse as Lua 5.2:\n{errors}\n--- lua ---\n{lua}");
    }
}

/// Assert a generator fragment parses: try as an expression, then as a statement.
#[track_caller]
pub fn assert_lua_fragment_parses(lua: &str) {
    let as_expr = format!("return ({lua})");
    if parse_errors(&as_expr).is_none() {
        return;
    }
    if parse_errors(lua).is_none() {
        return;
    }
    panic!(
        "emitted Lua fragment failed to parse as expression or statement:\n--- fragment ---\n{lua}"
    );
}

#[track_caller]
pub fn must_ok(result: Result<String, LuaGeneratorError>) -> String {
    let output = result.unwrap_or_else(|error| panic!("generate_module failed: {error:?}"));
    assert_lua_parses(&output);
    output
}

#[track_caller]
pub fn must_err(result: Result<String, LuaGeneratorError>) -> LuaGeneratorError {
    result.unwrap_err()
}

/// Emit a module, normalize the version header, snapshot, and parse-check.
///
/// Defined as a macro so `insta` records snapshots under the calling test file.
/// Import with `#[macro_use] mod common;`.
#[allow(unused_macros)]
macro_rules! assert_module_snapshot {
    ($name:expr, $result:expr) => {{
        let output = common::must_ok($result);
        let normalized = common::normalize_generated_header(&output);
        ::insta::assert_snapshot!($name, normalized);
    }};
}
