use factorio_codegen::LuaGenerator;
use factorio_ir::{
    block::Block,
    function::Function,
    module::{ImportedItem, Module, ModuleImport, Symbol},
    scope::Scope,
    statement::Statement,
};

#[test]
fn generates_require_statements() {
    let module = Module {
        name: "on_init".to_string(),
        body: Block { statements: vec![] },
        imports: vec![ModuleImport {
            module: "player".to_string(),
            local: "player".to_string(),
            items: vec![ImportedItem {
                name: "MyPlayer".to_string(),
                local: "MyPlayer".to_string(),
            }],
        }],
        submodules: vec![],
        symbols: vec![Symbol {
            scope: Scope::Public,
            statement: Statement::FunctionDecl(Function {
                name: "on_init".to_string(),
                params: vec![],
                body: Block { statements: vec![] },
            }),
        }],
    };

    let output = LuaGenerator::new().generate_module(&module).unwrap();

    assert_eq!(
        output,
        concat!(
            "-- Generated by cargo-factorio@0.1.0\n",
            "-- Module: `on_init`\n",
            "local player = require(\"player\")\n",
            "local MyPlayer = player.MyPlayer\n",
            "\n",
            "local onInit = {}\n",
            "function onInit.on_init()\n",
            "end\n",
            "return onInit\n",
        )
    );
}
