use factorio_codegen::LuaGenerator;
use factorio_ir::{
    block::Block,
    function::{Function, Parameter},
    module::{Module, Symbol},
    scope::Scope,
    statement::Statement,
    r#type::Type,
};

#[test]
fn generates_method_with_self_using_colon_syntax() {
    let module = Module {
        name: "player_util".to_string(),
        body: Block { statements: vec![] },
        symbols: vec![Symbol {
            scope: Scope::Public,
            statement: Statement::FunctionDecl(Function {
                name: "reset".to_string(),
                params: vec![
                    Parameter {
                        name: "self".to_string(),
                        r#type: Type::Void,
                    },
                    Parameter {
                        name: "player".to_string(),
                        r#type: Type::Void,
                    },
                ],
                body: Block {
                    statements: vec![Statement::Return(None)],
                },
            }),
        }],
    };

    let output = LuaGenerator::new().generate_module(&module).unwrap();

    assert_eq!(
        output,
        concat!(
            "-- Generated by cargo-factorio@",
            env!("CARGO_PKG_VERSION"),
            "\n",
            "-- Module: `player_util`\n",
            "local playerUtil = {}\n",
            "function playerUtil:reset(player)\n",
            "\treturn\n",
            "end\n",
            "return playerUtil\n",
        )
    );
}
