mod common;

use common::must_ok;
use factorio_codegen::LuaGenerator;
use factorio_ir::{
    block::Block,
    function::{Function, Parameter},
    module::{Module, Symbol},
    scope::Scope,
    stage::Stage,
    statement::Statement,
    r#type::Type,
};

#[test]
fn generates_method_with_self_using_colon_syntax() {
    let module = Module {
        name: "player_util".to_string(),
        stage: Stage::Control,
        body: Block { statements: vec![] },
        imports: vec![],
        submodules: vec![],
        locales: vec![],
        pending_locales: vec![],
        vtables: vec![],
        symbols: vec![Symbol {
            scope: Scope::Public,
            statement: Statement::FunctionDecl(Function {
                name: "reset".to_string(),
                params: vec![
                    Parameter {
                        name: "self".to_string(),
                        r#type: Type::Void,
                        source_type: None,
                    },
                    Parameter {
                        name: "player".to_string(),
                        r#type: Type::Void,
                        source_type: None,
                    },
                ],
                body: Block {
                    statements: vec![Statement::Return(None)],
                },
                doc: None,
                debug: None,
                event: None,
                event_filter: None,
                export: None,
                inline: false,
            }),
        }],
    };

    let output = must_ok(LuaGenerator::new().generate_module(&module));

    assert_eq!(
        output,
        concat!(
            "-- Generated by factorio-rs@",
            env!("CARGO_PKG_VERSION"),
            "\n",
            "-- Module: `player_util`\n",
            "local playerUtil = {}\n",
            "function playerUtil:reset(player)\n",
            "\treturn\n",
            "end\n",
            "return playerUtil\n",
        )
    );
}

#[test]
fn builder_setters_use_colon_on_method_chains() {
    use factorio_ir::{
        expression::Expression, literal::Literal, module::Module, statement::Statement,
    };

    let module = Module {
        name: "gui".to_string(),
        stage: Stage::Control,
        body: Block {
            statements: vec![Statement::Expr(Expression::MethodCall {
                receiver: Box::new(Expression::MethodCall {
                    receiver: Box::new(Expression::Call {
                        func: Box::new(Expression::QualifiedPath {
                            segments: vec!["ScrollPane".to_string(), "new".to_string()],
                        }),
                        args: vec![],
                    }),
                    method: "vertical_scroll_policy".to_string(),
                    args: vec![Expression::Literal(Literal::String("auto".to_string()))],
                }),
                method: "child".to_string(),
                args: vec![Expression::Identifier("rows".to_string())],
            })],
        },
        imports: vec![],
        submodules: vec![],
        locales: vec![],
        pending_locales: vec![],
        vtables: vec![],
        symbols: vec![],
    };

    let output = must_ok(LuaGenerator::new().generate_module(&module));
    assert!(
        output.contains("ScrollPane.new():vertical_scroll_policy(\"auto\"):child(rows)"),
        "GUI builder setters must use colon so self is passed:\n{output}"
    );
}
