use factorio_codegen::LuaGenerator;
use factorio_frontend::parse_module;
use factorio_ir::{
    block::Block,
    expression::Expression,
    function::{Function, Parameter},
    literal::Literal,
    module::{Module, Symbol},
    scope::Scope,
    statement::Statement,
    r#type::Type,
};

const BOUND_DETECTOR_SOURCE: &str = r"
fn helper() -> i64 {
    return 1;
}

pub fn on_init(_event: ()) {
    let count: i32 = 0;
}
";

#[test]
fn parses_module_with_private_helper_and_exported_handler() {
    let module = parse_module(BOUND_DETECTOR_SOURCE, "bound_detector").unwrap();

    assert_eq!(
        module,
        Module {
            name: "bound_detector".to_string(),
            body: Block {
                statements: vec![Statement::FunctionDecl(Function {
                    name: "helper".to_string(),
                    params: vec![],
                    body: Block {
                        statements: vec![Statement::Return(Some(Expression::Literal(
                            Literal::Int(1),
                        )))],
                    },
                })],
            },
            symbols: vec![Symbol {
                scope: Scope::Public,
                statement: Statement::FunctionDecl(Function {
                    name: "on_init".to_string(),
                    params: vec![Parameter {
                        name: "_event".to_string(),
                        r#type: Type::Void,
                    }],
                    body: Block {
                        statements: vec![Statement::VariableDecl {
                            name: "count".to_string(),
                            ty: Type::Int,
                            value: Expression::Literal(Literal::Int(0)),
                        }],
                    },
                }),
            }],
            imports: vec![],
            submodules: vec![],
        }
    );
}

#[test]
fn parsed_module_generates_expected_lua() {
    let module = parse_module(BOUND_DETECTOR_SOURCE, "bound_detector").unwrap();
    let output = LuaGenerator::new().generate_module(&module).unwrap();

    assert_eq!(
        output,
        concat!(
            "-- Generated by cargo-factorio@0.1.0\n",
            "-- Module: `bound_detector`\n",
            "local function helper()\n",
            "\treturn 1\n",
            "end\n",
            "local boundDetector = {}\n",
            "function boundDetector.on_init(_event)\n",
            "\tlocal count = 0\n",
            "end\n",
            "return boundDetector\n",
        )
    );
}
