use std::path::Path;

use std::fmt::Write;

use factorio_ir::{module::Module, stage::Stage, statement::Statement};
use heck::AsLowerCamelCase;
use serde::Serialize;

use crate::{
    cargo_manifest::CargoPackage,
    config::{Config, ModConfig},
    error::{CliError, CliResult},
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EventRegistration {
    pub module: String,
    pub handler: String,
    pub event: String,
}

#[derive(Debug, Serialize)]
struct InfoJson<'a> {
    name: &'a str,
    version: &'a str,
    title: &'a str,
    author: &'a str,
    factorio_version: &'a str,
    dependencies: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    description: Option<&'a str>,
}

pub fn collect_event_registrations(module: &Module) -> Vec<EventRegistration> {
    if module.stage != Stage::Control {
        return Vec::new();
    }

    module
        .symbols
        .iter()
        .filter_map(|symbol| {
            let Statement::FunctionDecl(function) = &symbol.statement else {
                return None;
            };
            let event_name = function.event.as_ref()?;
            Some(EventRegistration {
                module: module.name.clone(),
                handler: function.name.clone(),
                event: event_name.clone(),
            })
        })
        .collect()
}

pub fn generate_control_lua(mod_name: &str, events: &[EventRegistration]) -> String {
    let mut output = format!(
        "-- Generated by factorio-rs@{}\n",
        env!("CARGO_PKG_VERSION"),
    );
    if events.is_empty() {
        output.push_str("-- No event handlers registered.\n");
        return output;
    }

    for event in events {
        let lua_module_path = event.module.replace('.', "/");
        let require_path = format!("__{mod_name}__/lua/{lua_module_path}");
        let table_name = module_lua_identifier(&event.module);
        let _ = writeln!(output, "local {table_name} = require(\"{require_path}\")");
        if event.event == "on_init" {
            let _ = writeln!(output, "script.on_init(function(event)");
        } else {
            let _ = writeln!(
                output,
                "script.on_event(defines.events.{}, function(event)",
                event.event
            );
        }
        let _ = writeln!(output, "\t{}.{}(event)", table_name, event.handler);
        let _ = writeln!(output, "end)");
        output.push('\n');
    }

    output
}

pub fn generate_info_json(package: &CargoPackage, mod_config: &ModConfig) -> CliResult<String> {
    let author = package.author_label();
    let factorio_version = mod_config.factorio_version.as_deref().unwrap_or("2.0");
    let base_dependency = format!("base >= {factorio_version}");
    let info = InfoJson {
        name: &package.name,
        version: &package.version,
        title: mod_config.title.as_deref().unwrap_or(&package.name),
        author: author.as_str(),
        factorio_version,
        dependencies: vec![base_dependency],
        description: mod_config.description.as_deref(),
    };

    serde_json::to_string_pretty(&info).map_err(|source| CliError::InfoJsonSerialize { source })
}

pub fn write_mod_manifests(
    output_dir: &Path,
    package: &CargoPackage,
    config: &Config,
    events: &[EventRegistration],
) -> CliResult<()> {
    let control_lua = generate_control_lua(&package.name, events);
    let info_json = generate_info_json(package, &config.r#mod)?;

    std::fs::write(output_dir.join("control.lua"), control_lua).map_err(|source| {
        CliError::WriteFile {
            path: output_dir.join("control.lua"),
            source,
        }
    })?;
    std::fs::write(output_dir.join("info.json"), info_json).map_err(|source| {
        CliError::WriteFile {
            path: output_dir.join("info.json"),
            source,
        }
    })?;

    Ok(())
}

fn module_lua_identifier(module_name: &str) -> String {
    AsLowerCamelCase(module_name.replace('.', "_")).to_string()
}

#[cfg(test)]
mod tests {
    use factorio_ir::{
        block::Block,
        function::Function,
        module::{Module, Symbol},
        scope::Scope,
        stage::Stage,
        statement::Statement,
    };

    use super::{collect_event_registrations, generate_control_lua};

    #[test]
    fn generates_control_lua_with_on_init_handler() {
        let module = Module {
            name: "control.on_init".to_string(),
            stage: Stage::Control,
            body: Block { statements: vec![] },
            imports: vec![],
            submodules: vec![],
            symbols: vec![Symbol {
                scope: Scope::Public,
                statement: Statement::FunctionDecl(Function {
                    name: "on_init".to_string(),
                    params: vec![],
                    body: Block { statements: vec![] },
                    doc: None,
                    debug: None,
                    event: Some("on_init".to_string()),
                }),
            }],
        };

        let events = collect_event_registrations(&module);
        let lua = generate_control_lua("hello_world", &events);

        assert!(lua.contains("require(\"__hello_world__/lua/control/on_init\")"));
        assert!(lua.contains("script.on_init(function(event)"));
        assert!(lua.contains("controlOnInit.on_init(event)"));
        assert!(lua.contains("end)"));
    }
}
